name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_trivya
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
    
    - name: Create test environment file
      run: |
        cat > .env.test << EOF
        ENVIRONMENT=testing
        DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_trivya
        REDIS_URL=redis://localhost:6379/0
        SECRET_KEY=test_secret_key_change_in_production
        JWT_SECRET_KEY=test_jwt_secret_key_change_in_production
        ENCRYPTION_KEY=test_encryption_key_change_in_production
        OPENAI_API_KEY=test_openai_key
        ANTHROPIC_API_KEY=test_anthropic_key
        LOG_LEVEL=DEBUG
        EOF
    
    - name: Run linting
      run: |
        pip install flake8 black isort
        flake8 shared/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 shared/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        black --check shared/
        isort --check-only shared/
    
    - name: Run type checking
      run: |
        pip install mypy
        mypy shared/ --ignore-missing-imports
    
    - name: Run tests with coverage
      env:
        ENV_FILE: .env.test
      run: |
        pytest tests/ -v --cov=shared --cov-report=xml --cov-report=html --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella